name: Deploy Docs to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@a82c349d744aae9913f1a41a597ea753f96b3030
